### ISSUE TITLE
followup tracking issues from #95

### ISSUE THREAD

**Issue by MHBauer** [openservicebrokerapi/servicebroker#97]
- [ ]   The broker API has since been versioned to 2.10. Rebase or submit an additional PR with 2.10 changes?

- [x]    Why were the sections on the version header and authentication removed? Don't these deserve some explanation? They appear in example curls, but there is no other explanation. How should the broker author know what their responsibilities are?

- [ ]    With the exception of the table of contents, none of the links work.

- [x]    The example response body for Provision contains "dashboard\_url". The backslash should be removed. This may have been in an older version of github.com/cloudfoundry/docs-services but has since been fixed there.

- [x]    The first paragraph of the intro for Updating a Service Instance is out of date. I recall rewriting that some time ago.

- [x]    The whole section titled "Manage Application Requests with Route Services" can be removed. This link appears in the index of the current docs, but I've just sent a PR to remove it. This topic is for marketplace end-users (app developers), not for service broker authors. cloudfoundry/docs-services#145

- [x]    Remove the whole section titled "Volume Services (Experimental/Obsolete)" and fix the link in TOB for "Volume Services (Experimental)"

- [x]    You can remove the section "Using cf curl" under Access Control, as well as instructions to get the api version. I've just submitted a PR to docs-services to do the same. cloudfoundry/docs-services#147

**Comment by shalako** [comment]
Submitted #99 to address most of these. Submitted Issue #100 to fix links. Submitted issue #101 to update with latest changes from docs-services. 

I think with those three in place, this could be closed?

**Comment by shalako** [comment]
closing
